"""
Site copy, English/Hungarian pairs: T[key] = (en, hu).

Ported from the design repo's copy.py (magic-mountain-design). Keys whose value
is a fixed instance of a hike (a title, a date, a price...) were dropped here:
those now come from the Notion Hikes database at build time. Everything that is
part of the site's fixed chrome and voice is kept verbatim. A handful of keys
were added for things the mockup didn't need to say (form validation, empty
states, newsletter confirmation) written in the same plain voice.
"""

T = {
    # navigation, shared
    "nav_up": ("Upcoming hikes", "Következő túrák"),
    "nav_past": ("Past hikes", "Korábbi túrák"),
    "nav_about": ("About us", "Rólunk"),
    "nav_cta": ("Sign up for a hike", "Jelentkezem túrára"),
    "adults": ("Adults", "Felnőtt"),
    "families": ("Families", "Családi"),
    "tbc": ("Dates to be confirmed", "Időpont hamarosan"),
    "waiting": ("Waiting list", "Várólista"),
    "upcoming": ("Upcoming", "Hamarosan"),
    "past_tag": ("Past hike", "Korábbi túra"),
    "details": ("Hike details", "Részletek"),
    "join_wait": ("Join waiting list", "Várólistára"),
    "sign_up_short": ("Sign up", "Jelentkezés"),
    "per_person": ("/ person", "/ fő"),
    "per_adult": ("/ adult", "/ felnőtt"),
    "skip_link": ("Skip to content", "Ugrás a tartalomhoz"),
    "menu_open": ("Open menu", "Menü megnyitása"),
    "menu_close": ("Close menu", "Menü bezárása"),

    # home
    "hero_eyebrow": ("Guided hikes · Carpathians, Tatras, Caucasus", "Vezetett túrák · Kárpátok, Tátra, Kaukázus"),
    "hero_title": ("Small groups. <br>Real mountains. Quiet paths.", "Kis csoport. <br>Igazi hegyek. <br>Csendes ösvények."),
    "hero_lead": ("Multi-day hikes for adults and for families with small children, led by a certified international mountain leader, on carefully chosen routes.", "Többnapos túrák felnőtteknek és kisgyerekes családoknak, nemzetközi hegyi túravezető vezetésével, gondosan kiválasztott útvonalakon."),
    "hero_cta": ("See upcoming hikes", "Következő túrák"),
    "hero_cta2": ("How we hike", "Hogyan túrázunk"),
    "up_eyebrow": ("Upcoming hikes", "Következő túrák"),
    "up_title": ("Next departures", "Következő indulások"),
    "up_link": ("All upcoming hikes →", "Összes következő túra →"),
    "up_empty": ("No hikes have dates yet. Leave your email below and we'll write as soon as the next ones are set.", "Még egyetlen túrának sincs időpontja. Hagyd itt az e-mail-címed lent, és írunk, amint megvannak a következők."),
    "how_eyebrow": ("How we hike", "Hogyan túrázunk"),
    "how_title": ("What you can count on", "Amire számíthatsz"),
    "how1t": ("Routes chosen with care", "Gondosan választott útvonalak"),
    "how1": ("Every hike is planned around the group it is for: the distance, the ascent, the huts, and where we turn back if the weather says so.", "Minden túrát a csoporthoz tervezünk: a táv, a szintemelkedés, a szállás, és hogy hol fordulunk vissza, ha az időjárás úgy kívánja."),
    "how2t": ("Small groups", "Kis csoportok"),
    "how2": ("Small enough to move at one pace, eat at one table, and actually talk to each other by the second day.", "Elég kicsi ahhoz, hogy egy tempóban haladjunk, egy asztalnál együnk, és a második napra tényleg beszélgessünk."),
    "how3t": ("Places with a story", "Helyek, amiknek története van"),
    "how3": ("We prefer the quieter corners: less-visited valleys, huts and guesthouses run by locals, a castle or a cave on the way when there is one.", "A csendesebb helyeket keressük: kevésbé látogatott völgyeket, helyiek által vitt menedékházakat és vendégházakat, útba eső várat vagy barlangot, ha akad."),
    "cert": ("Led by a UIMLA-certified International Mountain Leader and member of the Romanian mountain guides' society (SGLM).", "UIMLA-minősítésű nemzetközi hegyi túravezető és a román hegyi vezetők társaságának (SGLM) tagja vezeti."),
    "past_eyebrow": ("Past hikes", "Korábbi túrák"),
    "past_title": ("Where we've been", "Ahol már jártunk"),
    "past_link": ("All past hikes →", "Összes korábbi túra →"),
    "past_empty": ("Our first hikes are still ahead of us — check back after we've been somewhere.", "Az első túráink még előttünk vannak — nézz vissza, ha már jártunk valahol."),
    "dan_eyebrow": ("The guide", "A túravezető"),
    "dan_cta": ("More about Dan", "Többet Danről"),
    "dan_text": ("Certified UIMLA International Mountain Leader and member of the Romanian mountain guides' society (SGLM). Has been walking the Carpathians, Tatras and Caucasus for [XX] years; leads the adult hikes and plans every route.", "UIMLA-minősítésű nemzetközi hegyi túravezető, a román hegyi vezetők társaságának (SGLM) tagja. [XX] éve járja a Kárpátokat, a Tátrát és a Kaukázust; ő vezeti a felnőtt túrákat és tervezi az útvonalakat."),
    "anett_eyebrow": ("Family hikes", "Családi túrák"),
    "anett_cta": ("More about Anett", "Többet Anettről"),
    "anett_text": ("Yoga teacher, mother of two, and the one who plans the family weekends: short walking days, snack stops, and something for the kids to remember at the end. She also runs Családi kalandozások a Bükkben, hikes in the Bükk for mums with small children.", "Jógaoktató, két gyerek anyukája, és ő tervezi a családi hétvégéket: rövid túranapok, uzsonnaszünetek, és valami, amire a gyerekek emlékezni fognak. Ő viszi a Családi kalandozások a Bükkben oldalt is: bükki túrák kisgyerekes anyukáknak."),
    "photo_dan": ("[PHOTO OF DAN]", "[DAN FOTÓJA]"),
    "photo_anett": ("[PHOTO OF ANETT]", "[ANETT FOTÓJA]"),
    "nl_eyebrow": ("Newsletter", "Hírlevél"),
    "nl_title": ("Hear about new dates first", "Tudd meg elsőként az új időpontokat"),
    "nl_lead": ("We announce new hikes by email before they go on Facebook. Family hikes fill fast; this is how you get in early.", "Az új túrákat e-mailben jelentjük be, mielőtt Facebookra kerülnének. A családi túrák gyorsan betelnek; így kerülhetsz be korán."),
    "nl_ph": ("you@example.com", "te@pelda.hu"),
    "nl_cta": ("Sign me up", "Feliratkozom"),
    "nl_note": ("A few emails a year, only when new hikes get dates. No spam, and you can unsubscribe with one click.", "Évente néhány e-mail, csak amikor új túráknak lesz időpontja. Nincs spam, egy kattintással leiratkozhatsz."),
    "nl_label": ("Email address", "E-mail cím"),
    "nl_pending": ("Almost there — check your inbox to confirm your subscription.", "Már majdnem kész — nézd meg a postaládád, és erősítsd meg a feliratkozást."),
    "nl_error": ("Something went wrong. Please try again in a moment.", "Valami elromlott. Kérjük, próbáld újra egy kicsit később."),

    # footer
    "f_desc": ("Guided hikes in Romania, Slovakia, Hungary and Georgia. Based in Noszvaj, Hungary.", "Vezetett túrák Romániában, Szlovákiában, Magyarországon és Grúziában. Bázisunk: Noszvaj."),
    "f_hikes": ("Hikes", "Túrák"),
    "f_signup": ("Sign up", "Jelentkezés"),
    "f_contact": ("Contact", "Kapcsolat"),
    "f_email": ("magicmountain.pro@gmail.com", "magicmountain.pro@gmail.com"),
    "f_wa": ("WhatsApp: [PHONE]", "WhatsApp: [TELEFON]"),
    "f_follow": ("Follow", "Kövess minket"),
    "f_legal": ("Legal", "Jogi"),
    "f_terms": ("Terms and refunds", "Feltételek és lemondás"),
    "f_privacy": ("Privacy notice", "Adatkezelés"),
    "f_insurance": ("Insurance", "Biztosítás"),
    "f_rights": ("Magic Mountain · magicmountain.pro", "Magic Mountain · magicmountain.pro"),

    # hike list page
    "l_eyebrow": ("Upcoming hikes", "Következő túrák"),
    "l_title": ("Where we're going next", "Merre megyünk legközelebb"),
    "l_lead": ("Every hike we currently have dates for. Family hikes and adult hikes are marked; if something is full, the waiting list is real and we do call people from it.", "Minden túra, aminek már van időpontja. A családi és a felnőtt túrákat jelöljük; ha valami betelt, a várólista valódi, és tényleg hívunk róla embereket."),
    "l_all": ("All", "Mind"),
    "past_lead": ("A record of the hikes we've run, kept honest for people deciding whether the next one is for them.", "Feljegyzés a megtartott túráinkról, őszintén, azoknak, akik eldöntenék, nekik való-e a következő."),
    "l_nl_eyebrow": ("Nothing that fits?", "Nincs, ami passzol?"),
    "l_nl_title": ("Hear about new dates first", "Tudd meg elsőként az új időpontokat"),
    "l_nl_lead": ("New hikes go out by email before Facebook. Leave your address and we'll write when the next ones are set.", "Az új túrák e-mailben mennek ki, mielőtt Facebookra kerülnének. Hagyd itt a címed, és írunk, amikor megvannak a következők."),

    # hike page, shared labels
    "h_dates": ("Dates", "Időpont"),
    "h_diff": ("Difficulty", "Nehézség"),
    "h_meet": ("Meeting point", "Találkozó"),
    "h_by": ("Sign up by", "Jelentkezés"),
    "h_price": ("Price", "Ár"),
    "h_the": ("The hike", "A túra"),
    "h_like": ("What this one is like", "Milyen ez a túra"),
    "h_itin": ("Itinerary", "Program"),
    "h_daybyday": ("Day by day", "Napról napra"),
    "h_day": ("Day", "nap"),
    "h_prac": ("Practical", "Gyakorlati"),
    "h_get": ("Getting there and what to bring", "Odajutás és felszerelés"),
    "h_incl": ("Included in the price", "Az ár tartalmazza"),
    "h_i1": ("Certified guide on all days", "Minősített túravezető minden nap"),
    "h_i2": ("Route planning and safety", "Útvonaltervezés és biztonság"),
    "h_i3": ("Booking the accommodation for the group", "A csoport szállásának lefoglalása"),
    "h_i4": ("Packing list and pre-trip briefing", "Felszereléslista és túra előtti eligazítás"),
    "h_sep": ("Paid separately", "Külön fizetendő"),
    "h_acc": ("Accommodation:", "Szállás:"),
    "h_own": ("Travel to the meeting point, meals, personal gear and travel insurance (required) are yours to arrange.", "Az utazás a találkozási pontig, az étkezés, a személyes felszerelés és az utasbiztosítás (kötelező) a te dolgod."),
    "h_cta": ("Sign up for this hike", "Jelentkezem erre a túrára"),
    "h_dep": ("A deposit holds your place; the balance is due before departure. Details in the", "Előleggel foglalható a hely, a többi indulás előtt esedékes. Részletek a"),
    "h_q": ("Questions? Write to", "Kérdésed van? Írj:"),
    "h_q2": ("or message on WhatsApp.", "vagy írj WhatsAppon."),
    "h_full": ("This hike is full. Join the waiting list and we will call you if a place opens up.", "Ez a túra betelt. Iratkozz fel a várólistára, és szólunk, ha felszabadul egy hely."),
    "h_places_left": ("places left", "szabad hely"),

    # hike page, past
    "p_high": ("High point", "Csúcs"),
    "p_group": ("Group", "Csoport"),
    "p_base": ("Base", "Bázis"),
    "p_how": ("How it went", "Hogy sikerült"),
    "p_how_t": ("A short, honest account", "Rövid, őszinte beszámoló"),
    "p_photos": ("More photos from the trip", "További fotók a túráról"),
    "p_nl_eyebrow": ("Want to do this one?", "Te is jönnél?"),
    "p_nl_title": ("We may run it again", "Lehet, hogy újra megyünk"),
    "p_nl_lead": ("Leave your email and we'll tell you when the next dates are set, before they go on Facebook.", "Hagyd itt az e-mail-címed, és szólunk, amikor megvan a következő időpont, még a Facebook előtt."),

    # about
    "a_eyebrow": ("About us", "Rólunk"),
    "a_title": ("Two people, two kids, one dog, a lot of mountains", "Két ember, két gyerek, egy kutya, sok hegy"),
    "a_lead": ("Magic Mountain is Dan and Anett. We moved from Budapest to Noszvaj, at the foot of the Bükk hills, to be closer to the places we keep going back to. This is what we do with the rest of our time.", "A Magic Mountain Dan és Anett. Budapestről költöztünk Noszvajra, a Bükk lábához, hogy közelebb legyünk azokhoz a helyekhez, ahová újra és újra visszajárunk. Ezt csináljuk a maradék időnkben."),
    "a_dan_role": ("Guide · UIMLA International Mountain Leader", "Túravezető · UIMLA nemzetközi hegyi túravezető"),
    "a_dan1": ("I have been walking in the mountains for most of my life, and guiding groups since I qualified as a UIMLA International Mountain Leader in [YEAR]. I'm a member of the Romanian mountain guides' society (SGLM), which is also where our pricing comes from.", "Életem nagy részében hegyekben jártam, csoportokat pedig azóta vezetek, hogy [ÉV]-ben UIMLA nemzetközi hegyi túravezető lettem. A román hegyi vezetők társaságának (SGLM) tagja vagyok; az árazásunk is onnan ered."),
    "a_dan2": ("I plan every route around the group that's coming: how long the days really take, where the water is, and where we get off the ridge if the weather turns. Where I can, I walk it first.", "Minden útvonalat az érkező csoporthoz tervezek: mennyi ideig tart valójában egy nap, hol van víz, és hol jövünk le a gerincről, ha fordul az idő. Ahol tudom, előre bejárom."),
    "a_dan3": ("The rest of the week I'm a UX researcher, which is a long way of saying I ask a lot of questions and I listen to the answers. It turns out to be useful on a hike too.", "A hét többi napján UX-kutató vagyok, ami hosszabban annyit tesz: sokat kérdezek, és meghallgatom a válaszokat. Kiderült, hogy túrán is hasznos."),
    "a_anett_role": ("Family trips · Yoga · Marketing", "Családi túrák · Jóga · Marketing"),
    "a_anett1": ("I'm a yoga teacher and I look after the family side of Magic Mountain: the weekends where the kids set the pace and the grown-ups get to slow down. I also run the marketing, so if you found us on Instagram, that was me. Closer to home, I organise Családi kalandozások a Bükkben: short hikes in the Bükk for mums with small children, no guide certificate required, just good company and a lookout tower at the end.", "Jógaoktató vagyok, és a Magic Mountain családi oldalát viszem: azokat a hétvégéket, ahol a gyerekek diktálják a tempót, a felnőttek pedig lelassulhatnak. A marketing is az enyém, szóval ha Instagramon találtál ránk, az én voltam. Itthon a Családi kalandozások a Bükkben túráit szervezem: rövid bükki túrák kisgyerekes anyukáknak, túravezetői papír nélkül, jó társasággal és egy kilátóval a végén."),
    "a_anett2": ("We have two small children ourselves, so every family trip is planned by someone who has carried a tired four-year-old down a hill. Short legs, snack stops and a lookout tower at the end are not afterthoughts; they are the plan.", "Nekünk is két kicsi gyerekünk van, így minden családi túrát olyan valaki tervez, aki már vitt le fáradt négyévest a hegyről. A rövid lábak, az uzsonnaszünetek és a kilátó a végén nem utólagos ötletek: ez maga a terv."),
    "a_why": ("Why we do this", "Miért csináljuk"),
    "a_why_t": ("The mountains change how you see things", "A hegyek megváltoztatják, hogyan látsz"),
    "a_why1": ("A few days of walking, with no signal and nothing to decide except when to stop for lunch, does something to people. We've watched it happen enough times to trust it: how you see yourself, how you handle hard things, what you think you need.", "Néhány nap gyaloglás, térerő nélkül, ahol az egyetlen döntés az, mikor álljunk meg ebédelni, tesz valamit az emberrel. Elégszer láttuk már, hogy higgyünk benne: hogyan látod magad, hogyan bírod a nehezet, mit hiszel, hogy kell neked."),
    "a_why2": ("So we pick places that tell a story, historical, cultural or simply geological, and where we can, ones the crowds haven't found. We keep groups small. We stay in huts and guesthouses run by locals. And we try to send everyone home with three things: dramatic landscapes, unexpected discoveries, and sincere human connection.", "Ezért olyan helyeket választunk, amiknek története van, történelmi, kulturális vagy egyszerűen geológiai, és ahol lehet, olyat, amit a tömeg még nem talált meg. Kicsik a csoportjaink. Helyiek által vitt menedékházakban és vendégházakban alszunk. És három dolgot próbálunk hazaküldeni mindenkivel: drámai tájakat, váratlan felfedezéseket és őszinte emberi kapcsolatot."),
    "a_c1t": ("UIMLA International Mountain Leader", "UIMLA nemzetközi hegyi túravezető"),
    "a_c1": ("The international standard for leading groups in non-glaciated mountain terrain. #weareuimla", "A nemzetközi szabvány csoportok vezetésére gleccsermentes hegyi terepen. #weareuimla"),
    "a_c2t": ("SGLM, Romania", "SGLM, Románia"),
    "a_c2": ("Societatea Ghizilor și Liderilor Montani. We guide at the society's professional rates. #societateaghizilor", "Societatea Ghizilor și Liderilor Montani. A társaság szakmai díjszabása szerint vezetünk. #societateaghizilor"),
    "a_c3t": ("Romania, Slovakia, Hungary, Georgia", "Románia, Szlovákia, Magyarország, Grúzia"),
    "a_c3": ("Weekend trips in the Hungarian and Slovak hills to week-long treks in the Carpathians and the Caucasus.", "Hétvégi túrák a magyar és szlovák hegyekben, egyhetes trekkek a Kárpátokban és a Kaukázusban."),

    # sign-up
    "s_eyebrow": ("Sign up", "Jelentkezés"),
    "s_title": ("Save your place", "Foglald le a helyed"),
    "s_lead": ("Takes two minutes. We confirm by email within a day or two, with the deposit details and what happens next.", "Két perc az egész. Egy-két napon belül e-mailben visszaigazoljuk, az előleg részleteivel és a további teendőkkel."),
    "s_1": ("1 · The hike", "1 · A túra"),
    "s_which": ("Which hike?", "Melyik túra?"),
    "s_which_empty": ("No hikes are open for sign-up right now.", "Jelenleg egyetlen túrára sem lehet jelentkezni."),
    "s_adults": ("Adults", "Felnőtt"),
    "s_children": ("Children (under 16)", "Gyerek (16 év alatt)"),
    "s_2": ("2 · Who you are", "2 · Ki vagy"),
    "s_name": ("Full name", "Teljes név"),
    "s_email": ("Email", "E-mail"),
    "s_phone": ("Phone (WhatsApp)", "Telefon (WhatsApp)"),
    "s_phone_h": ("For the group chat and day-of contact.", "A csoportos csethez és a túranapi kapcsolathoz."),
    "s_from": ("Where are you travelling from?", "Honnan indulsz?"),
    "s_from_h": ("Helps us match up shared cars.", "Segít összehozni a telekocsikat."),
    "s_3": ("3 · Fitness and notes", "3 · Erőnlét és megjegyzések"),
    "s_fit": ("Your longest mountain day this year", "Az idei leghosszabb hegyi napod"),
    "s_fit_opts": (
        ["Under 3 hours", "3–6 hours", "6–8 hours", "8+ hours", "Haven't done one yet"],
        ["3 óra alatt", "3–6 óra", "6–8 óra", "8+ óra", "Még nem volt ilyen"],
    ),
    "s_notes": ("Anything we should know?", "Bármi, amit tudnunk kell?"),
    "s_notes_ph": ("Dietary preferences, kids' ages, questions about the hike…", "Étkezési szokások, gyerekek kora, kérdések a túráról…"),
    "s_notes_h": ("Please don't write health details here. If something matters for the hike, we'll ask privately before departure.", "Kérjük, egészségügyi adatot ne írj ide. Ha valami fontos a túrához, indulás előtt négyszemközt megkérdezzük."),
    "s_chk1": ("I have read the <a href=\"{terms}\">terms, refund and insurance rules</a>, I understand this hike has real physical demands, and I will have travel insurance that covers it.", "Elolvastam a <a href=\"{terms}\">feltételeket, a lemondási és biztosítási szabályokat</a>, tudom, hogy ez a túra valódi fizikai megterhelést jelent, és lesz rá érvényes utasbiztosításom."),
    "s_chk2": ("I agree to Magic Mountain storing my details to organise this hike. <a href=\"{terms}#privacy\">Privacy notice</a>", "Hozzájárulok, hogy a Magic Mountain a túra szervezéséhez tárolja az adataimat. <a href=\"{terms}#privacy\">Adatkezelési tájékoztató</a>"),
    "s_send": ("Send my sign-up", "Jelentkezés elküldése"),
    "s_sending": ("Sending…", "Küldés…"),
    "s_nopay": ("No payment now. Deposit request comes with the confirmation.", "Most nem kell fizetni. Az előlegkérés a visszaigazolással jön."),
    "s_next": ("What happens next", "Mi történik ezután"),
    "s_n1t": ("We reply within 1–2 days", "1–2 napon belül válaszolunk"),
    "s_n1": ("A personal email, not an auto-responder. If the hike is full, we say so and offer the waiting list.", "Személyes e-mail, nem automata. Ha a túra betelt, megmondjuk, és felajánljuk a várólistát."),
    "s_n2t": ("A deposit to hold your place", "Előleg a hely biztosításához"),
    "s_n2": ("Bank transfer. Refund rules are on the terms page.", "Banki átutalás. A visszatérítés szabályai a feltételek oldalon."),
    "s_n3t": ("Packing list and group chat", "Felszereléslista és csoportos chat"),
    "s_n3": ("Two weeks out you get the kit list, the car-share plan and a short call to answer questions.", "Két héttel indulás előtt jön a felszereléslista, a telekocsi-terv és egy rövid hívás a kérdésekre."),
    "s_n4t": ("Balance before departure", "A többi indulás előtt"),
    "s_n4": ("The rest of the price from the hike page; we send a reminder.", "A túraoldalon szereplő ár többi része; küldünk emlékeztetőt."),
    "s_talk": ("Rather talk first? Message Dan on WhatsApp at", "Inkább beszélnél előbb? Írj Dannek WhatsAppon:"),
    "s_ok_title": ("Thank you — we've got your sign-up", "Köszönjük — megkaptuk a jelentkezésed"),
    "s_ok_text": ("We reply by email within 1–2 days with the deposit details and what happens next.", "1–2 napon belül e-mailben válaszolunk az előleg részleteivel és a további teendőkkel."),
    "s_err": ("Something went wrong sending your sign-up. Please try again, or write to", "Valami elromlott a jelentkezés küldése közben. Kérjük, próbáld újra, vagy írj:"),
    "s_required": ("Please fill in this field.", "Kérjük, töltsd ki ezt a mezőt."),
    "s_email_invalid": ("Please enter a valid email address.", "Kérjük, adj meg érvényes e-mail-címet."),
    "s_hike_prefix": ("Signing up for:", "Jelentkezés erre:"),

    # policies
    "pol_eyebrow": ("Terms, refunds and insurance", "Feltételek, lemondás és biztosítás"),
    "pol_title": ("The boring but important page", "Az unalmas, de fontos oldal"),
    "pol_lead": ("Plain-language terms for booking a hike with Magic Mountain. Last updated [DD Month YYYY]. Draft: to be reviewed before publishing.", "Közérthető feltételek a Magic Mountain túráira való jelentkezéshez. Utolsó frissítés: [ÉÉÉÉ. hónap NN.]. Vázlat: közzététel előtt ellenőrizendő."),
    "pol_toc": ("On this page", "Ezen az oldalon"),

    "pol1t": ("1 · Booking and payment", "1 · Jelentkezés és fizetés"),
    "pol1": ([
        "Your place is confirmed when we have received your sign-up and the deposit of [XX 000] Ft (or [XX]% of the hike price). We confirm by email within [2] working days.",
        "The price on each hike page is for guiding and organisation only, per person, in Hungarian forint. Accommodation is booked by us for the group and passed on to the host at cost; we tell you the amount before you pay. You arrange your own travel to the meeting point.",
        "The balance is due [3] weeks before departure. Payment is by bank transfer to [ACCOUNT HOLDER, IBAN]. We do not take card payments on the site."],
        ["A helyed akkor biztos, amikor megkaptuk a jelentkezésed és a [XX 000] Ft (vagy a túraár [XX]%-ának megfelelő) előleget. [2] munkanapon belül e-mailben visszaigazoljuk.",
         "A túraoldalakon szereplő ár kizárólag a vezetést és a szervezést tartalmazza, fejenként, forintban. A szállást mi foglaljuk le a csoportnak, és önköltségen továbbítjuk a szállásadónak; az összeget fizetés előtt közöljük. A találkozási pontig az utazást te szervezed.",
         "A fennmaradó összeg [3] héttel indulás előtt esedékes. Fizetés banki átutalással: [SZÁMLATULAJDONOS, IBAN]. Az oldalon nem fogadunk el kártyás fizetést."]),
    "pol2t": ("2 · Cancellation and refunds", "2 · Lemondás és visszatérítés"),
    "pol2": ([
        "If you cancel more than [4] weeks before departure, we refund everything except [X 000] Ft for administration.",
        "Between [4] and [2] weeks before departure, we refund [50]% of what you have paid.",
        "Less than [2] weeks before departure, or if you don't turn up, no refund; if we can fill your place from the waiting list we refund [everything except the deposit].",
        "You can always pass your place to someone else who meets the fitness requirements of the hike, at no cost. Tell us in writing."],
        ["Ha több mint [4] héttel indulás előtt mondod le, mindent visszatérítünk [X 000] Ft ügyintézési díj kivételével.",
         "Indulás előtt [4] és [2] hét között a befizetett összeg [50]%-át térítjük vissza.",
         "Kevesebb mint [2] héttel indulás előtt, vagy ha nem jelensz meg, nincs visszatérítés; ha a várólistáról be tudjuk tölteni a helyed, [az előleg kivételével mindent] visszatérítünk.",
         "A helyedet bármikor, díjmentesen átadhatod valakinek, aki megfelel a túra erőnléti feltételeinek. Írásban szólj."]),
    "pol3t": ("3 · If we cancel or change a hike", "3 · Ha mi mondunk le vagy módosítunk"),
    "pol3": ([
        "Mountain weather decides some things for us. We may shorten, reroute or postpone a hike for safety; in that case there is no refund for the days walked, and we pass back any accommodation money the host returns.",
        "If we cancel a hike before it starts, for any reason including too few participants (we decide [X] weeks before departure), you get a full refund or a place on another date, your choice. We are not liable for travel you booked separately."],
        ["A hegyi időjárás néhány dolgot helyettünk dönt el. Biztonsági okból rövidíthetjük, módosíthatjuk vagy elhalaszthatjuk a túrát; ilyenkor a megtett napokra nincs visszatérítés, a szállásadó által visszaadott szállásdíjat pedig továbbadjuk.",
         "Ha a túrát indulás előtt mi mondjuk le, bármilyen okból, például kevés jelentkező miatt (erről [X] héttel indulás előtt döntünk), teljes visszatérítést vagy helyet kapsz egy másik időpontra, ahogy szeretnéd. A külön foglalt utazásodért nem vállalunk felelősséget."]),
    "pol4t": ("4 · Insurance", "4 · Biztosítás"),
    "pol4": ([
        "You must have travel insurance that covers hiking in the mountains we are visiting, including mountain rescue and repatriation. Bring the policy number; we ask for it on the pre-trip form.",
        "In Romania, Slovakia and Georgia mountain rescue is [free / not free] and medical care is not; the European Health Insurance Card only covers state care in EU countries.",
        "Magic Mountain holds professional liability insurance for guiding ([INSURER, POLICY NUMBER]). It does not cover your belongings or your own accidents."],
        ["Kötelező olyan utasbiztosítás, amely kiterjed a meglátogatott hegyekben való túrázásra, a hegyimentésre és a hazaszállításra is. Hozd magaddal a kötvényszámot; a túra előtti űrlapon elkérjük.",
         "Romániában, Szlovákiában és Grúziában a hegyimentés [ingyenes / nem ingyenes], az orvosi ellátás nem; az Európai Egészségbiztosítási Kártya csak az EU-s országok állami ellátására érvényes.",
         "A Magic Mountain szakmai felelősségbiztosítással rendelkezik a túravezetésre ([BIZTOSÍTÓ, KÖTVÉNYSZÁM]). Ez nem terjed ki a személyes tárgyaidra és a saját baleseteidre."]),
    "pol5t": ("5 · Your responsibilities on the hike", "5 · A te felelősséged a túrán"),
    "pol5": ([
        "You confirm that you are fit for the hike as described on its page, and that you have told us about any condition that could matter in the mountains. If in doubt, ask us before you sign up.",
        "The guide's decisions on route, pace and turning back are final. A participant who repeatedly ignores them may be asked to leave the hike, with no refund.",
        "Hiking involves inherent risks that no guide can remove. Beyond our professional duty of care, you take part at your own risk."],
        ["Kijelented, hogy a túraoldalon leírt túrára alkalmas vagy, és elmondtál nekünk mindent, ami a hegyekben számíthat. Ha bizonytalan vagy, kérdezz, mielőtt jelentkezel.",
         "A túravezető döntése az útvonalról, a tempóról és a visszafordulásról végleges. Aki ezeket ismételten figyelmen kívül hagyja, azt megkérhetjük, hogy hagyja el a túrát, visszatérítés nélkül.",
         "A túrázás olyan kockázatokkal jár, amelyeket egyetlen túravezető sem tud megszüntetni. Szakmai gondosságunkon túl saját felelősségedre veszel részt."]),
    "pol6t": ("6 · Children", "6 · Gyerekek"),
    "pol6": ([
        "On family hikes, a parent or guardian is responsible for their children at all times. The age guidance on each family hike page is a real minimum, not a suggestion.",
        "A parent or guardian signs the participation statement for each child."],
        ["Családi túrákon a gyerekekért mindvégig a szülő vagy gondviselő felel. A családi túraoldalakon szereplő korhatár valódi minimum, nem javaslat.",
         "A részvételi nyilatkozatot minden gyerek nevében a szülő vagy gondviselő írja alá."]),
    "pol7t": ("7 · Privacy notice (GDPR)", "7 · Adatkezelési tájékoztató (GDPR)"),
    "pol7": ([
        "What we collect: your name, email, phone number, where you travel from, the number of adults and children, and your answers about hiking experience, only to organise the hike you signed up for. We don't ask for health details on the website; if something matters for your safety, we ask you privately before departure and delete it after the hike.",
        "Where it is kept: sign-ups go straight into a private Google Sheet in the Magic Mountain Google account, which is protected with two-step verification and shared with nobody outside the two organisers. The website itself stores nothing: it is a set of static pages with no user accounts, no tracking and no advertising cookies.",
        "Newsletter: if you subscribe, only your email address goes to our mailing-list provider (Mailchimp), after you confirm it in a first email. Every newsletter has a one-click unsubscribe link.",
        "How long: sign-up details are deleted [12] months after the hike. Newsletter addresses are kept until you unsubscribe. We never sell or pass on your details. Photos from the hike appear on our social media only if you say yes.",
        "Your rights: you can ask to see, correct or delete your data any time at magicmountain.pro@gmail.com, and you can complain to the Hungarian data protection authority (NAIH). Data controller: [NAME, ADDRESS, TAX NUMBER]."],
        ["Mit kezelünk: a nevedet, e-mail-címedet, telefonszámodat, indulási helyedet, a felnőttek és gyerekek számát és a túratapasztalatodra adott válaszaidat, kizárólag annak a túrának a szervezéséhez, amelyre jelentkeztél. Egészségügyi adatot a weboldalon nem kérünk; ha valami a biztonságod miatt fontos, indulás előtt négyszemközt megkérdezzük, és a túra után töröljük.",
         "Hol tároljuk: a jelentkezések közvetlenül a Magic Mountain Google-fiókjának egy privát Google-táblázatába kerülnek. A fiókot kétlépcsős azonosítás védi, és a két szervezőn kívül senkivel nincs megosztva. Maga a weboldal semmit nem tárol: statikus oldalakból áll, felhasználói fiókok, követés és hirdetési sütik nélkül.",
         "Hírlevél: ha feliratkozol, csak az e-mail-címed kerül a hírlevél-szolgáltatónkhoz (Mailchimp), miután egy első levélben megerősítetted. Minden hírlevélben van egykattintásos leiratkozás.",
         "Meddig: a jelentkezési adatokat a túra után [12] hónappal töröljük. A hírlevél-címeket a leiratkozásig őrizzük. Az adataidat soha nem adjuk el és nem adjuk tovább. A túrán készült fotók csak a hozzájárulásoddal kerülnek a közösségi oldalainkra.",
         "Jogaid: bármikor kérheted az adataid megtekintését, javítását vagy törlését a magicmountain.pro@gmail.com címen, és panaszt tehetsz a Nemzeti Adatvédelmi és Információszabadság Hatóságnál (NAIH). Adatkezelő: [NÉV, CÍM, ADÓSZÁM]."]),
    "pol8t": ("8 · Contact", "8 · Kapcsolat"),
    "pol8": (["[NAME], trading as Magic Mountain · [ADDRESS] · [TAX NUMBER] · magicmountain.pro@gmail.com · [PHONE]"],
              ["[NÉV], Magic Mountain néven · [CÍM] · [ADÓSZÁM] · magicmountain.pro@gmail.com · [TELEFON]"]),

    # meta / seo
    "meta_home_title": ("Magic Mountain — guided hikes in the Carpathians, Tatras and Caucasus", "Magic Mountain — vezetett túrák a Kárpátokban, a Tátrában és a Kaukázusban"),
    "meta_home_desc": ("Small-group, multi-day guided hikes for adults and families, led by a certified international mountain leader.", "Kis csoportos, többnapos vezetett túrák felnőtteknek és családoknak, nemzetközi hegyi túravezető vezetésével."),
    "meta_hikes_title": ("Upcoming hikes — Magic Mountain", "Következő túrák — Magic Mountain"),
    "meta_past_title": ("Past hikes — Magic Mountain", "Korábbi túrák — Magic Mountain"),
    "meta_about_title": ("About us — Magic Mountain", "Rólunk — Magic Mountain"),
    "meta_signup_title": ("Sign up — Magic Mountain", "Jelentkezés — Magic Mountain"),
    "meta_policies_title": ("Terms and refunds — Magic Mountain", "Feltételek és lemondás — Magic Mountain"),
    "meta_404_title": ("Page not found — Magic Mountain", "Az oldal nem található — Magic Mountain"),
    "404_title": ("Page not found", "Az oldal nem található"),
    "404_text": ("This trail doesn't exist. Try the homepage, or the upcoming hikes.", "Ez az ösvény nem létezik. Próbáld a főoldalt, vagy a következő túrákat."),
    "404_home": ("Back to the homepage", "Vissza a főoldalra"),

    # interaction layer: places meter, deadline countdown, filters, gallery, phone menu
    "left_of": ("{left} of {total} places left", "{total} helyből {left} szabad"),
    "full_wait": ("Full · waiting list open", "Betelt · várólista nyitva"),
    "left_short": ("{left} places left", "{left} szabad hely"),
    "dl_closes": ("Sign-up closes in", "Jelentkezési határidő"),
    "dl_days": ("days", "nap"),
    "dl_hours": ("hours", "óra"),
    "fl_diff": ("Difficulty", "Nehézség"),
    "fl_month": ("Month", "Hónap"),
    "fl_any": ("Any", "Mind"),
    "g_all": ("See all {n} photos", "Mind a {n} fotó"),
    "g_more": ("+{n} photos", "+{n} fotó"),
    "g_swipe": ("Swipe for the next photo", "Húzd el a következő fotóhoz"),
    "m_note": ("No payment now. We confirm by email.", "Most nem kell fizetni. E-mailben visszaigazoljuk."),

    "difficulty_easy": ("Easy", "Könnyű"),
    "difficulty_moderate": ("Moderate", "Közepes"),
    "difficulty_demanding": ("Demanding", "Nehéz"),
}

DIFFICULTY_KEYS = {"Easy": "difficulty_easy", "Moderate": "difficulty_moderate", "Demanding": "difficulty_demanding"}


def t(key, lang):
    val = T[key]
    if isinstance(val, tuple) and len(val) == 2 and not isinstance(val[0], list):
        return val[0] if lang == "en" else val[1]
    return val


def tl(key, lang):
    """Same as t() but for keys whose value is a pair of lists (paragraphs, options)."""
    en, hu = T[key]
    return en if lang == "en" else hu
